spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

source:
  blog:
    daum:
      url: https://dapi.kakao.com/v2/search/blog
      apiKey: "KakaoAK 77162c195c842ef9e5fa02ab865bb976"
    #naver:
